[project]
name = "repozitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "app>=0.0.1",
    "fastapi>=0.115.13",
    "unicorn>=2.1.3",
    "uvicorn>=0.34.3",
]
